### ISSUE TITLE
Memory leak on serverdemo

### ISSUE THREAD

**Issue by nomorelogic** [jbsolucoes/ceosmw#2]
hi
I found a memory leak in demo server, unit ceosserver
to verify:
1) compile with heaptrace
2) click on the start button
3) click on Stop
4) click on the start button a second time
5) click on the stop button again
closing the application you will have a memory leak

to allow activation/deactivation more than once, I would suggest this change

```
procedure TCeosServer.Start;
begin
  try
    if not Assigned(FThrdHTTPServer) then   // <- add this "if" statement
       FThrdHTTPServer := THTTPServerThread.Create(Port, Threaded, @DoOnRequest, OnException);
    //FThrdHTTPServer.FreeOnTerminate := true;
    FActive := FThrdHTTPServer.Active;

    if FActive and Assigned(OnStart) then
      OnStart(Self);

  except on e:exception do
    if Assigned(OnException) then
      OnException(Self,e)
    else
      raise exception.create(e.message);
  end;
end;

**Comment by jbsolucoes** [comment]
Fixed. Thanks for help!

Best regards
JB
