### ISSUE TITLE
Custom error codes?

### ISSUE THREAD

**Issue by MFernstrom** [jbsolucoes/ceosmw#3]
How can we pass custom error codes?

**Comment by jbsolucoes** [comment]
By default, JSONRPC error codes specification in ceosconsts.pas (http://www.jsonrpc.org/specification#response_object)

You can call JSONRPCError function (ceostypes.pas) and pass custom error codes.

Best regards
JB

**Comment by MFernstrom** [comment]
Great, thanks!

**Comment by MFernstrom** [comment]
Sorry, quick question, how would I do this from a TCeosServerMethod (Such as Test in appmethods.pas)?

**Comment by jbsolucoes** [comment]
something like?

```
TMyMethods = class(TCeosServerMethods)
  published
    function Test(Request: TCeosRequestContent): TJSONStringType;
end;
...
function TMyMethods.Test(Request: TCeosRequestContent): TJSONStringType;
begin
  try
    result := 'My Result';
  except
    result := JSONRPCError(-444, 'Error Details');
  end;
end;
```

**Comment by MFernstrom** [comment]
I tried that, I get

`Error: Incompatible types: got "TCeosResponseContent" expected "UTF8String"`

**Comment by jbsolucoes** [comment]
result := JSONRPCError(-444, 'Error Details').AsJSON;

**Comment by jbsolucoes** [comment]
Otherwise you need change in TCeosServerMethods response

**Comment by MFernstrom** [comment]
Aha, yes that did it (Doh!).

That should be fine for what I need it for.

Apart from that, nice framework! It's working great so far.

**Comment by jbsolucoes** [comment]
Thanks so mutch :)

Best regards
